/* The following code was generated by JFlex 1.4.3 on 21/08/15 00:00 */


package br.com.jonjts.lexico;

import java_cup.runtime.*;
import java.io.IOException;
import br.com.jonjts.entity.*;

// import br.com.jonjts.lexico.ScannerSym;
// import static br.com.jonjts.lexico.ScannerSym.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21/08/15 00:00 from the specification file
 * <tt>C:/Users/Jonas/workspace/LEX/scanner.lex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CHECK_BEGIN_END = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\57\1\57\2\0\1\57\22\0\1\1\7\0\1\44\1\45"+
    "\1\54\1\52\1\56\1\53\1\5\1\55\12\3\1\46\1\0\1\47"+
    "\1\51\1\50\2\0\1\7\1\2\1\21\1\2\1\16\2\2\1\12"+
    "\1\20\2\2\1\10\1\15\1\13\1\2\1\11\1\2\1\17\2\2"+
    "\1\14\5\2\4\0\1\4\1\0\1\33\1\37\1\2\1\34\1\27"+
    "\1\26\1\2\1\36\1\23\2\2\1\30\1\2\1\24\1\40\1\42"+
    "\1\2\1\32\1\31\1\25\1\43\1\41\1\35\3\2\1\6\1\0"+
    "\1\22\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\2\14\4"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\1\1\21\1\22\1\0\1\4"+
    "\1\23\11\4\1\24\2\4\1\25\2\0\1\26\1\27"+
    "\5\4\1\30\5\4\1\0\1\31\1\4\1\32\1\33"+
    "\1\34\2\4\1\35\1\36\1\37\1\0\1\40\1\41"+
    "\1\42\11\0\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\u0300\0\u0330\0\u0360\0\u0390\0\140\0\140\0\u03c0\0\140"+
    "\0\140\0\140\0\140\0\140\0\140\0\140\0\140\0\u03f0"+
    "\0\u0420\0\u0120\0\u0450\0\u0480\0\300\0\u04b0\0\u04e0\0\u0510"+
    "\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\300\0\u0660"+
    "\0\u0690\0\140\0\u0420\0\u06c0\0\300\0\300\0\u06f0\0\u0720"+
    "\0\u0750\0\u0780\0\u07b0\0\300\0\u07e0\0\u0810\0\u0840\0\u0870"+
    "\0\u08a0\0\u08d0\0\300\0\u0900\0\300\0\300\0\300\0\u0930"+
    "\0\u0960\0\300\0\300\0\300\0\u0990\0\300\0\300\0\300"+
    "\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10"+
    "\0\u0b40\0\140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\7\1\10\13\5"+
    "\1\3\1\11\1\12\1\13\1\14\1\15\2\5\1\16"+
    "\1\17\1\5\1\20\1\5\1\21\1\22\1\23\1\24"+
    "\1\5\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\4\1\40\1\41\56\40"+
    "\61\0\1\4\55\0\1\4\2\0\3\5\2\0\13\5"+
    "\1\0\21\5\17\0\1\6\1\0\1\42\55\0\1\42"+
    "\63\0\1\43\52\0\3\5\2\0\13\5\1\0\1\5"+
    "\1\44\1\5\1\45\15\5\16\0\3\5\2\0\13\5"+
    "\1\0\15\5\1\46\3\5\16\0\3\5\2\0\13\5"+
    "\1\0\7\5\1\47\11\5\16\0\3\5\2\0\13\5"+
    "\1\0\10\5\1\50\10\5\16\0\3\5\2\0\13\5"+
    "\1\0\5\5\1\51\13\5\16\0\3\5\2\0\13\5"+
    "\1\0\4\5\1\52\14\5\16\0\3\5\2\0\13\5"+
    "\1\0\1\5\1\53\17\5\16\0\3\5\2\0\13\5"+
    "\1\0\7\5\1\54\3\5\1\55\5\5\16\0\3\5"+
    "\2\0\13\5\1\0\15\5\1\56\3\5\16\0\3\5"+
    "\2\0\13\5\1\0\7\5\1\57\11\5\16\0\3\5"+
    "\2\0\13\5\1\0\15\5\1\60\3\5\16\0\3\5"+
    "\2\0\13\5\1\0\10\5\1\61\10\5\65\0\1\62"+
    "\6\0\61\40\1\63\56\40\10\0\1\64\51\0\3\5"+
    "\2\0\13\5\1\0\2\5\1\65\16\5\16\0\3\5"+
    "\2\0\13\5\1\0\2\5\1\66\16\5\16\0\3\5"+
    "\2\0\13\5\1\0\20\5\1\67\16\0\3\5\2\0"+
    "\13\5\1\0\5\5\1\70\13\5\16\0\3\5\2\0"+
    "\13\5\1\0\1\71\5\5\1\72\12\5\16\0\3\5"+
    "\2\0\13\5\1\0\10\5\1\73\10\5\16\0\3\5"+
    "\2\0\13\5\1\0\11\5\1\74\7\5\16\0\3\5"+
    "\2\0\13\5\1\0\1\75\20\5\16\0\3\5\2\0"+
    "\13\5\1\0\1\76\20\5\16\0\3\5\2\0\13\5"+
    "\1\0\15\5\1\77\3\5\16\0\3\5\2\0\13\5"+
    "\1\0\1\100\20\5\16\0\3\5\2\0\13\5\1\0"+
    "\6\5\1\101\12\5\25\0\1\102\50\0\3\5\2\0"+
    "\13\5\1\0\4\5\1\103\14\5\16\0\3\5\2\0"+
    "\13\5\1\0\6\5\1\104\12\5\16\0\3\5\2\0"+
    "\13\5\1\0\3\5\1\105\15\5\16\0\3\5\2\0"+
    "\13\5\1\0\4\5\1\106\14\5\16\0\3\5\2\0"+
    "\13\5\1\0\11\5\1\107\7\5\16\0\3\5\2\0"+
    "\13\5\1\0\2\5\1\110\16\5\16\0\3\5\2\0"+
    "\13\5\1\0\5\5\1\111\13\5\16\0\3\5\2\0"+
    "\13\5\1\0\5\5\1\112\13\5\16\0\3\5\2\0"+
    "\13\5\1\0\11\5\1\113\7\5\16\0\3\5\2\0"+
    "\13\5\1\0\6\5\1\114\12\5\26\0\1\115\47\0"+
    "\3\5\2\0\13\5\1\0\4\5\1\116\14\5\16\0"+
    "\3\5\2\0\13\5\1\0\4\5\1\117\14\5\16\0"+
    "\3\5\2\0\13\5\1\0\4\5\1\120\14\5\23\0"+
    "\1\121\54\0\1\122\66\0\1\123\60\0\1\124\60\0"+
    "\1\125\60\0\1\126\60\0\1\127\60\0\1\130\60\0"+
    "\1\131\60\0\1\132\35\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2928];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\21\1\2\11\1\1\10\11\3\1"+
    "\1\0\16\1\1\11\2\0\15\1\1\0\12\1\1\0"+
    "\3\1\11\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

	private BeginEndStack bes = new BeginEndStack();
	private Token token(Token.T type){
		return new Token(type, yyline, yycolumn);
	}
	
	private Token token(Token.T type, Object val){
		return new Token(type, val, yyline, yycolumn);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { yybegin(YYINITIAL); return bes.checkSpace(yytext(),yyline, yycolumn);
          }
        case 36: break;
        case 2: 
          { System.err.println("Illegal character: ' " + yytext() + " '");
          }
        case 37: break;
        case 18: 
          { return token(Token.T.FLOAT, yytext());
          }
        case 38: break;
        case 21: 
          { return token(Token.T.ATRIBUICAO, yytext());
          }
        case 39: break;
        case 8: 
          { return token(Token.T.DOIS_PONTOS, yytext());
          }
        case 40: break;
        case 30: 
          { return token(Token.T.VOID, yytext());
          }
        case 41: break;
        case 35: 
          { return token(Token.T.COMENTARIO, yytext());
          }
        case 42: break;
        case 16: 
          { return token(Token.T.VIRGULA, yytext());
          }
        case 43: break;
        case 19: 
          { return token(Token.T.IF, yytext());
          }
        case 44: break;
        case 12: 
          { return token(Token.T.MAIS, yytext());
          }
        case 45: break;
        case 1: 
          { yybegin(YYINITIAL);
          }
        case 46: break;
        case 7: 
          { return token(Token.T.FECHA_PARENTESE, yytext());
          }
        case 47: break;
        case 5: 
          { return token(Token.T.INTEGER, yytext());
          }
        case 48: break;
        case 28: 
          { return token(Token.T.READ, yytext());
          }
        case 49: break;
        case 9: 
          { return token(Token.T.MENOR_QUE, yytext());
          }
        case 50: break;
        case 32: 
          { return token(Token.T.FALSE, yytext());
          }
        case 51: break;
        case 14: 
          { return token(Token.T.VEZES, yytext());
          }
        case 52: break;
        case 27: 
          { return token(Token.T.ELSE, yytext());
          }
        case 53: break;
        case 15: 
          { return token(Token.T.DIVIDIR, yytext());
          }
        case 54: break;
        case 29: 
          { return token(Token.T.BOOL, yytext());
          }
        case 55: break;
        case 25: 
          { return token(Token.T.TRUE, yytext());
          }
        case 56: break;
        case 23: 
          { return token(Token.T.NOT, yytext());
          }
        case 57: break;
        case 34: 
          { return token(Token.T.WHILE, yytext());
          }
        case 58: break;
        case 10: 
          { return token(Token.T.MAIOR_QUE, yytext());
          }
        case 59: break;
        case 26: 
          { return token(Token.T.ELIF, yytext());
          }
        case 60: break;
        case 33: 
          { return token(Token.T.WRITE, yytext());
          }
        case 61: break;
        case 13: 
          { return token(Token.T.MENOS, yytext());
          }
        case 62: break;
        case 6: 
          { return token(Token.T.ABRE_PARENTESE, yytext());
          }
        case 63: break;
        case 22: 
          { return token(Token.T.INT, yytext());
          }
        case 64: break;
        case 31: 
          { return token(Token.T.PASS, yytext());
          }
        case 65: break;
        case 24: 
          { return token(Token.T.AND, yytext());
          }
        case 66: break;
        case 11: 
          { return token(Token.T.IGUALDADE, yytext());
          }
        case 67: break;
        case 3: 
          { /* do nothing */
          }
        case 68: break;
        case 20: 
          { return token(Token.T.OR, yytext());
          }
        case 69: break;
        case 4: 
          { return token(Token.T.ID, yytext());
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return token(Token.T.EOF);
            }
            case 91: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
